In [7]:
import numpy as np
import pandas as pd
import networkx as nx
import csv
import matplotlib.pyplot as plt

In [9]:
my_data = np.genfromtxt('RoadsData/BerlinNetwork.txt', skip_header = 9)
mylist = ['Init_node','Term_node','Capacity','Length','Free_Flow','Time','B','Power','Speed_limit','Toll','Type']
#~ 	Init node 	Term node 	Capacity 	Length 	Free Flow Time 	B 	Power 	Speed limit 	Toll 	Type 	;

In [10]:
my_data.shape

(28376, 11)

In [11]:
df = pd.DataFrame(my_data, columns= mylist)

In [12]:
df.mean()

Init_node        6147.635044
Term_node        6151.203200
Capacity       311679.333028
Length            189.295038
Free_Flow           5.380063
Time                1.379335
B                   4.000000
Power               0.000000
Speed_limit         0.000000
Toll                0.689667
Type                     NaN
dtype: float64

In [13]:
df

,Init_node,Term_node,Capacity,Length,Free_Flow,Time,B,Power,Speed_limit,Toll,Type
0,1.0,11000.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
1,1.0,11007.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
2,1.0,11704.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
3,1.0,11708.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
4,1.0,11717.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
5,2.0,10892.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
6,2.0,10895.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
7,2.0,11707.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
8,2.0,11711.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
9,2.0,11714.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
10,3.0,3336.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
11,3.0,3361.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
12,3.0,10256.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
13,3.0,11293.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
14,3.0,12313.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
15,4.0,12363.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
16,4.0,12685.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
17,4.0,12690.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
18,4.0,12799.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
19,4.0,12800.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
20,5.0,11696.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
21,5.0,11697.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
22,5.0,11698.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
23,5.0,11714.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
24,5.0,11725.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
25,6.0,11016.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
26,6.0,11017.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
27,6.0,11695.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28,6.0,11717.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
29,6.0,11724.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
28346,12976.0,4784.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28347,12976.0,4951.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28348,12976.0,4952.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28349,12976.0,4953.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28350,12976.0,4956.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28351,12977.0,1002.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28352,12977.0,6116.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28353,12977.0,6173.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28354,12977.0,6174.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28355,12977.0,6175.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28356,12978.0,5623.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28357,12978.0,5624.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28358,12978.0,5744.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28359,12978.0,5872.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28360,12978.0,5874.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28361,12979.0,6013.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28362,12979.0,6014.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28363,12979.0,6015.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28364,12979.0,6122.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28365,12979.0,6123.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28366,12980.0,993.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28367,12980.0,994.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28368,12980.0,5698.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28369,12980.0,5703.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28370,12980.0,5711.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28371,12981.0,4474.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28372,12981.0,4523.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28373,12981.0,6771.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28374,12981.0,6776.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN
28375,12981.0,6777.0,999999.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,NaN

In [14]:
with open('edglist.csv', 'w') as csvfile:
    for items in my_data:
        csvfile.write(str(items[0]) + "," + str(items[1]) + "\n")

In [15]:
fh=open("edglist.csv", 'rb')
G=nx.read_edgelist(fh,delimiter = ",")

In [16]:
def read_graph(file_path):

    g = nx.DiGraph()
    file = open(file_path,'r')
    
    for line in file:
        split = line.split(',')
        n1 = int(float(split[0].strip()))
        n2 = int(float(split[1].strip()))
        capacity = float(split[2].strip())
        length = float(split[3].strip())
        free_flow_time = float(split[4].strip())
        b = float(split[5].strip())
        power = float(split[6].strip())
        speed_limit = float(split[7].strip())
        toll = float(split[8].strip())
        edge_type = float(split[9].strip())
        
        if n1 not in g.nodes():
            g.add_node(n1, color = 'b', size = 50)
        
        if n2 not in g.nodes():
            g.add_node(n2,color='b', size=50)
        
        g.add_edge(n1,
                   n2,
                   capacity=capacity,
                   length=length, 
                   free_flow_time=free_flow_time,
                   b=b,
                   power=power,
                   speed_limit=speed_limit,
                   toll=toll,
                   edge_type=edge_type)
            
    file.close()
    return g

In [17]:
graph = read_graph("RoadsData/mitte-center-network.txt")

#nodes = []
#edges = {}
#file = open("edglist.csv",'r')

#for line in file:
#    split = line.split(',')
#    n1 = int(float(split[0].strip()))
#    n2 = int(float(split[1].strip()))
#    graph.add_edge(n1,n2)
            
#file.close()

#color = nx.get_node_attributes(graph,'color')
#size = nx.get_node_attributes(graph,'size')

#nx.draw(graph,
#        node_size= 0,
#        width=0.04,
#        with_labels=False)
#plt.show(graph)

ValueError: could not convert string to float: '<NUMBER OF ZONES> 36'